#!/bin/bash

set -e

npm run docs

pushd docs &> /dev/null
git init
git config user.name "AutoBot"
git config user.email "dylan947@gmail.com"
git add -A
git commit -m "Deploy to GitHub pages"
git push --force "https://${GH_TOKEN}@${GH_REF}" master
popd &> /dev/null
